# Generated by Django 3.2.9 on 2021-11-08 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('ClassId', models.AutoField(primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('StuentName', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('ClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentsApp.classes')),
            ],
        ),
    ]
